name: Unit Tests
on: 
  workflow_dispatch: {}
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.2'
    - name: Check out code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        go mod download
    - name: Run Integration tests
      env:
        GROQ_KEY: ${{ secrets.GROQ_KEY }}
        TOOLHOUSE_API_KEY: ${{ secrets.TOOLHOUSE_API_KEY }}
        E2B_API_KEY: ${{ secrets.E2B_API_KEY }}
      run: |
        go test -race -tags=integration ./...
    - name: Run Unit tests
      env:
        GROQ_KEY: ${{ secrets.GROQ_KEY }}
        TOOLHOUSE_API_KEY: ${{ secrets.TOOLHOUSE_API_KEY }}
        E2B_API_KEY: ${{ secrets.E2B_API_KEY }}
        UNIT: true
      run: |
        go test -race -covermode atomic -coverprofile=covprofile ./...
